// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Data;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations.TaskManagement
{
    [DbContext(typeof(TaskManagementDbContext))]
    [Migration("20251117060232_FixManagerEmployeeColumnLengths")]
    partial class FixManagerEmployeeColumnLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tasks")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Copy the model from the previous migration's Designer
            // This migration only alters column types in the database
            // The model structure remains the same as MakeAzureAdObjectIdNullable
            
            // Note: The actual model snapshot (TaskManagementDbContextModelSnapshot.cs) 
            // reflects the current state with nvarchar(256) for ManagerEmployee columns
#pragma warning restore 612, 618
        }
    }
}

